import type { MenuItem } from "./types";

export const menuItems: MenuItem[] = [
  {
    id: "papas-chili-cheese",
    name: "Papas Chili Cheese",
    description: "Papas a la francesa cubiertas con salsa de carne y queso.",
    price: 110,
    category: "entradas",
    image: "/images/menu/papas-chili-cheese.jpg",
  },
  {
    id: "alitas-6",
    name: "Alitas (6)",
    description: "6 alitas fritas, servidas con ranch. Opciones: Buffalo mild, lemon pepper, garlic parmesan o BBQ.",
    price: 100,
    category: "entradas",
    image: "/images/menu/alitas-6.jpg",
  },
  {
    id: "pepinillos-fritos",
    name: "Pepinillos Fritos",
    description: "Una canasta de pepinillos fritos servidos con ranch.",
    price: 100,
    category: "entradas",
    image: "/images/menu/pepinillos-fritos.jpg",
  },
  {
    id: "nachos",
    name: "Nachos",
    description: "Totopos frescos con una cama de frijoles, pollo desmenuzado o carne molida con queso rallado. Encima jalapeños, lechuga, pico de gallo y crema ácida.",
    price: 155,
    category: "entradas",
    image: "/images/menu/nachos.jpg",
    spiceLevel: 2,
  },
  {
    id: "aros-de-cebolla",
    name: "Aros de Cebolla",
    description: "Aros grandes de cebolla fritos.",
    price: 90,
    category: "entradas",
    image: "/images/menu/aros-de-cebolla.jpg",
    vegetarian: true,
  },
  {
    id: "champinones-fritos",
    name: "Champiñones Fritos",
    description: "Frescos champiñones fritos hechos con nuestra masa de la casa. Servidos con ranch.",
    price: 110,
    category: "entradas",
    image: "/images/menu/champinones-fritos.jpg",
    vegetarian: true,
  },
  {
    id: "ensalada-del-chef",
    name: "Ensalada del Chef",
    description: "Mezcla de lechuga y vegetales, cubierta de jamón, pavo, huevo cocido y queso rallado.",
    price: 180,
    category: "ensaladas",
    image: "/images/menu/ensalada-del-chef.jpg",
  },
  {
    id: "ensalada-de-pollo",
    name: "Ensalada de Pollo",
    description: "Mezcla de lechuga y vegetales, cubierta de pechuga de pollo a la plancha o frita, queso rallado.",
    price: 205,
    category: "ensaladas",
    image: "/images/menu/ensalada-de-pollo.jpg",
  },
  {
    id: "ensalada-crispy",
    name: "Ensalada Crispy",
    description: "Lechuga con una cama de frijoles y carne de su preferencia, cubierta de queso rallado y pico de gallo. Servida en tortilla de harina frita en forma de canasta.",
    price: 200,
    category: "ensaladas",
    image: "/images/menu/ensalada-crispy.jpg",
  },
  {
    id: "club-sandwich",
    name: "Club Sándwich",
    description: "Sándwich de 3 panes con jamón de pierna, jamón de pavo, tocino, queso, lechuga, jitomate y mayonesa. Servido con papas a la francesa o aros de cebolla.",
    price: 125,
    category: "sandwich-hamburguesas",
    image: "/images/menu/club-sandwich.jpg",
    featured: true,
  },
  {
    id: "hamburguesa",
    name: "Hamburguesa",
    description: "Hamburguesa tradicional casera 1/3 libra de carne. Servida con papas a la francesa o aros de cebolla.",
    price: 145,
    category: "sandwich-hamburguesas",
    image: "/images/menu/hamburguesa.jpg",
  },
  {
    id: "hamburguesa-jalapeno",
    name: "Hamburguesa Jalapeño",
    description: "Hamburguesa casera 1/3 libra de carne. Cubierta de cebolla asada, jalapeños frescos y queso pepper Jack, servida con papas a la francesa o aros de cebolla.",
    price: 155,
    category: "sandwich-hamburguesas",
    image: "/images/menu/hamburguesa-jalapeno.jpg",
    spiceLevel: 2,
  },
  {
    id: "hamburguesa-chili",
    name: "Hamburguesa Chili",
    description: "Hamburguesa casera, cubierta de nuestra salsa de carne, y queso, servida con papas a la francesa o aros de cebolla.",
    price: 165,
    category: "sandwich-hamburguesas",
    image: "/images/menu/hamburguesa-chili.jpg",
  },
  {
    id: "chili-cheese-dog-con-papas",
    name: "Chili Cheese Dog con Papas",
    description: "Hot dog jumbo con nuestra salsa de carne, queso, y cebolla. Servido con papas a la francesa.",
    price: 165,
    category: "sandwich-hamburguesas",
    image: "/images/menu/chili-cheese-dog-con-papas.jpg",
  },
  {
    id: "hamburguesa-de-pollo",
    name: "Hamburguesa de Pollo",
    description: "Pechuga de pollo a la plancha o frita. Servido con papas a la francesa o aros de cebolla.",
    price: 140,
    category: "sandwich-hamburguesas",
    image: "/images/menu/hamburguesa-de-pollo.jpg",
  },
  {
    id: "hamburguesa-queso-tocino",
    name: "Hamburguesa de Queso y Tocino",
    description: "Hamburguesa casera 1/3 libra de carne. Tocino crujiente, queso. Servida con papas a la francesa o aros de cebolla.",
    price: 160,
    category: "sandwich-hamburguesas",
    image: "/images/menu/hamburguesa-queso-tocino.jpg",
  },
  {
    id: "hamburguesa-champinones-jack",
    name: "Hamburguesa Champiñones Jack",
    description: "Hamburguesa casera 1/3 libra de carne. Cubierta de champiñones a la parrilla y queso Jack, servida con papas a la francesa o aros de cebolla.",
    price: 155,
    category: "sandwich-hamburguesas",
    image: "/images/menu/hamburguesa-champinones-jack.jpg",
  },
  {
    id: "hamburguesa-hawaiana",
    name: "Hamburguesa Hawaiana",
    description: "Hamburguesa casera, piña, jamón, queso pepper Jack. Servida con papas a la francesa o aros de cebolla.",
    price: 170,
    category: "sandwich-hamburguesas",
    image: "/images/menu/hamburguesa-hawaiana.jpg",
  },
  {
    id: "hot-dog-sencillo",
    name: "Hot Dog Sencillo",
    description: "Hot dog jumbo con cebolla, jalapeño, ketchup, y mostaza. Servido con papas a la francesa.",
    price: 100,
    category: "sandwich-hamburguesas",
    image: "/images/menu/hot-dog-sencillo.jpg",
    spiceLevel: 1,
  },
  {
    id: "cheesy-chicken",
    name: "Cheesy Chicken",
    description: "Pechuga de pollo frita bañada en nuestro queso de la casa, jitomate fresco, cebolla y pedacitos de tocino.",
    price: 225,
    category: "platos-fuertes",
    image: "/images/menu/cheesy-chicken.jpg",
  },
  {
    id: "tiras-de-pollo",
    name: "Tiras de Pollo",
    description: "4 tiras de pollo frito en nuestra masa de la casa, servidos con nuestra gravy casera.",
    price: 190,
    category: "platos-fuertes",
    image: "/images/menu/tiras-de-pollo.jpg",
  },
  {
    id: "chicken-fried-steak",
    name: "Chicken Fried Steak",
    description: "Nuestro especial de Texas! Tierno filete de res frito en nuestra masa de la casa, servido con nuestra gravy casera.",
    price: 200,
    category: "platos-fuertes",
    image: "/images/menu/chicken-fried-steak.jpg",
    featured: true,
  },
  {
    id: "chuleta",
    name: "Chuleta",
    description: "1 tierna chuleta de cerdo a elegir: a la parrilla o frita. (Frita es servida con gravy).",
    price: 180,
    category: "platos-fuertes",
    image: "/images/menu/chuleta.jpg",
  },
  {
    id: "pescado",
    name: "Pescado",
    description: "Filete de pescado basa fresco, a elegir frito en nuestra masa de la casa o a la parrilla en mantequilla, hierbas finas y especias.",
    price: 200,
    category: "platos-fuertes",
    image: "/images/menu/pescado.jpg",
  },
  {
    id: "pechuga-de-pollo-empanizada",
    name: "Pechuga de Pollo Empanizada",
    description: "Pechuga de pollo frita en nuestra masa de la casa, servida con nuestra gravy casera.",
    price: 195,
    category: "platos-fuertes",
    image: "/images/menu/pechuga-de-pollo-empanizada.jpg",
  },
  {
    id: "pechuga-de-pollo",
    name: "Pechuga de Pollo",
    description: "Pechuga de pollo a la parrilla en mantequilla, hierbas finas y especias.",
    price: 195,
    category: "platos-fuertes",
    image: "/images/menu/pechuga-de-pollo.jpg",
  },
  {
    id: "carne-de-hamburguesa",
    name: "Carne de Hamburguesa",
    description: "Carne de res en forma de filete a la parrilla bañada con champiñones y cebolla a la parrilla.",
    price: 195,
    category: "platos-fuertes",
    image: "/images/menu/carne-de-hamburguesa.jpg",
  },
  {
    id: "chimichanga",
    name: "Chimichanga",
    description: "Burrito frito tamaño Texas relleno de pollo deshebrado o fajita de res, cebolla y pimiento a la parrilla, queso rallado, frijoles, lechuga y pico de gallo, bañado a elegir entre nuestro queso derretido casero o nuestra salsa cremosa ranch jalapeño casera.",
    price: 155,
    category: "platos-tex-mex",
    image: "/images/menu/chimichanga.jpg",
    spiceLevel: 2,
    featured: true,
  },
  {
    id: "enchiladas-de-queso",
    name: "Enchiladas de Queso",
    description: "2 enchiladas de queso Colby Jack bañadas con nuestra chili sauce casera y queso gratinado. Acompañadas con arroz rojo, frijoles, lechuga y pico de gallo.",
    price: 150,
    category: "platos-tex-mex",
    image: "/images/menu/enchiladas-de-queso.jpg",
    vegetarian: true,
  },
  {
    id: "enchiladas-de-carne-de-res",
    name: "Enchiladas de Carne de Res",
    description: "2 enchiladas de carne molida, bañadas con nuestra chili sauce casera y queso gratinado. Acompañadas con arroz rojo, frijoles, lechuga y pico de gallo.",
    price: 150,
    category: "platos-tex-mex",
    image: "/images/menu/enchiladas-de-carne-de-res.jpg",
  },
  {
    id: "enchiladas-verdes",
    name: "Enchiladas Verdes",
    description: "2 enchiladas de pollo bañadas con salsa de tomate y queso gratinado. Acompañadas con arroz rojo, frijoles, lechuga y pico de gallo.",
    price: 155,
    category: "platos-tex-mex",
    image: "/images/menu/enchiladas-verdes.jpg",
  },
  {
    id: "crispy-tacos",
    name: "Crispy Tacos",
    description: "3 tortillas de maíz doradas en forma de taco. Su elección de carne: carne molida o pollo desmenuzado, con arroz rojo, frijoles.",
    price: 130,
    category: "platos-tex-mex",
    image: "/images/menu/crispy-tacos.jpg",
  },
  {
    id: "fajitas-de-carne-de-res",
    name: "Fajitas de Carne de Res",
    description: "Fajita de carne de res con cebolla y pimiento morrón asados. Acompañada con arroz rojo, frijoles, lechuga, pico de gallo, queso rallado, crema ácida y tortillas de harina o maíz.",
    price: 160,
    category: "platos-tex-mex",
    image: "/images/menu/fajitas-de-carne-de-res.jpg",
  },
  {
    id: "fajitas-de-pollo",
    name: "Fajitas de Pollo",
    description: "Fajita de pollo con cebolla y pimiento morrón asados. Acompañada con arroz rojo, frijoles, lechuga, pico de gallo, queso rallado, crema ácida y tortillas de harina o maíz.",
    price: 160,
    category: "platos-tex-mex",
    image: "/images/menu/fajitas-de-pollo.jpg",
  },
  {
    id: "quesadillas-tejanas",
    name: "Quesadillas Tejanas",
    description: "Su elección de carne. Frijoles y queso, hechas con tortilla de harina. Acompañadas con arroz rojo, frijoles, lechuga y pico de gallo.",
    price: 170,
    category: "platos-tex-mex",
    image: "/images/menu/quesadillas-tejanas.jpg",
  },
  {
    id: "coca-cola-600ml",
    name: "Coca-Cola 600Ml",
    description: "",
    price: 30,
    category: "bebidas",
    image: "/images/menu/coca-cola-600ml.jpg",
  },
  {
    id: "coca-light-600ml",
    name: "Coca Light 600Ml",
    description: "",
    price: 30,
    category: "bebidas",
    image: "/images/menu/coca-light-600ml.jpg",
  },
  {
    id: "sprite-600ml",
    name: "Sprite 600Ml",
    description: "",
    price: 30,
    category: "bebidas",
    image: "/images/menu/sprite-600ml.jpg",
  },
  {
    id: "dr-pepper-600ml",
    name: "Dr. Pepper 600Ml",
    description: "",
    price: 30,
    category: "bebidas",
    image: "/images/menu/dr-pepper-600ml.jpg",
  },
  {
    id: "orange-crush-600ml",
    name: "Orange Crush 600Ml",
    description: "",
    price: 30,
    category: "bebidas",
    image: "/images/menu/orange-crush-600ml.jpg",
  },
  {
    id: "sweet-tea-16oz",
    name: "Sweet Tea 16Oz",
    description: "Refrescante té endulzado, 16 oz.",
    price: 30,
    category: "bebidas",
    image: "/images/menu/sweet-tea-16oz.jpg",
  },
  {
    id: "agua-embotellada",
    name: "Agua Embotellada",
    description: "",
    price: 20,
    category: "bebidas",
    image: "/images/menu/agua-embotellada.jpg",
  },
  {
    id: "cherry-limeade-16oz",
    name: "Cherry Limeade 16Oz",
    description: "Soda de limón y cereza.",
    price: 39,
    category: "bebidas",
    image: "/images/menu/cherry-limeade-16oz.jpg",
  },
];
